++ dirname ./startserver.sh
+ BASEDIR=.
+ SCRIPTPATH=./../../rtun-routing
+ export PYTHONPATH=./../../torpy-rtun-fork/
+ PYTHONPATH=./../../torpy-rtun-fork/
+ python3 ./../../rtun-routing/rtun.py -v INFO -g staysafeandgoodluck -f rendezvous.txt -t peer1peer2 -n default -i 3 -d 2
Exception in thread Establish-GTAOnline3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Establish-neartAurora:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Thread-189:
Traceback (most recent call last):
Exception in thread Thread-188:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-191:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
