++ dirname ./startserver.sh
+ BASEDIR=.
+ SCRIPTPATH=./../../rtun-routing
+ export PYTHONPATH=./../../torpy-rtun-fork/
+ PYTHONPATH=./../../torpy-rtun-fork/
+ python3 ./../../rtun-routing/rtun.py -v INFO -g staysafeandgoodluck -f rendezvous.txt -t peer1peer2 -n default -i 2 -d 1
Exception in thread Thread-1233:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 679, in runDijkstra
    rp_node = rp_paths[prev_node][next_node]
KeyError: 'P3'
Exception in thread Thread-1237:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 679, in runDijkstra
    rp_node = rp_paths[prev_node][next_node]
KeyError: 'P3'
Exception in thread Establish-Stellvia:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 132, in run
    data = stream.recv(1024)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/stream.py", line 374, in recv
    raise Exception('recv timeout')
Exception: recv timeout
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
