++ dirname ./startserver.sh
+ BASEDIR=.
+ SCRIPTPATH=./../../rtun-routing
+ export PYTHONPATH=./../../torpy-rtun-fork/
+ PYTHONPATH=./../../torpy-rtun-fork/
+ python3 ./../../rtun-routing/rtun.py -v INFO -g staysafeandgoodluck -f rendezvous.txt -t peer1peer2 -n default -i 2 -d 1
Exception in thread Establish-Planetclaire61:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Establish-FreedomOfThought:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Establish-Planetclaire61:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Thread-162:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-164:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-169:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-171:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-177:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-179:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-181:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-183:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-185:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Thread-187:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Establish-TheBestRelayNick3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception in thread Thread-194:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 636, in shortest_paths
    cost = nx.path_weight(G, v, 'weight')
  File "/usr/local/lib/python3.9/dist-packages/networkx/classes/function.py", line 1291, in path_weight
    raise nx.NetworkXNoPath("path does not exist")
networkx.exception.NetworkXNoPath: path does not exist
Exception in thread Establish-onionDAOrel0aded1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 86, in run
    rendezvous2_cell = w.get(timeout=self.timeout)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 134, in get
    raise CellTimeoutError('Timeout wait for ' + cells_format(self._cell_types))
torpy.circuit.CellTimeoutError: Timeout wait for CellRelayRendezvous2
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
