++ dirname ./startserver.sh
+ BASEDIR=.
+ SCRIPTPATH=./../../rtun-routing
+ export PYTHONPATH=./../../torpy-rtun-fork/
+ PYTHONPATH=./../../torpy-rtun-fork/
+ python3 ./../../rtun-routing/rtun.py -v INFO -g staysafeandgoodluck -f rendezvous.txt -l -t peer1peer2 -n default -i 1 -d 2
/home/vboxuser/Git/imt4905/rtun-routing/lsr.py:525: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if args[3] is 1:
Traceback (most recent call last):
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 126, in run
    self.serverSide(queue_data)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 174, in serverSide
    self.handle_LOOKUP(local_copy_LSA)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 430, in handle_LOOKUP
    route_message(msg_data)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 1021, in route_message
    send_to_stream(dst_relay, pickle.dumps(msg_data))
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 1332, in send_to_stream
    rnd.snd_data(message,
  File "/home/vboxuser/Git/imt4905/rtun-routing/rendezvous.py", line 418, in snd_data
    extend_node.encrypt_forward(relay_cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/circuit.py", line 101, in encrypt_forward
    self._crypto_state.encrypt_forward(relay_cell)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/crypto_state.py", line 83, in encrypt_forward
    relay_cell.prepare(self._digesting_func)
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 240, in prepare
    payload = self._serialize_payload()
  File "/home/vboxuser/Git/imt4905/torpy-rtun-fork/torpy/cells.py", line 263, in _serialize_payload
    raise Exception(
Exception: relay payload length cannot be more than 498 (502 got)
Exception in thread Thread-184:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/vboxuser/Git/imt4905/rtun-routing/lsr.py", line 537, in updateGraphAfterFailure
    args[0].remove(node)
ValueError: list.remove(x): x not in list
Exception ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
